/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Projeto.Views;

import Projeto.Classes.RequisitosFuncionais;
import Projeto.Controllers.*;
import Projeto.Views.membros.*;
import java.awt.Dimension;
import javax.swing.ImageIcon;

/**
 *
 * @author Leonardo
 */
public class MembrosInstituicao extends javax.swing.JInternalFrame {
    
    AlunoController aluno;
    ProfessorController professor;
    TurmaController turma;
      
    public MembrosInstituicao( AlunoController aluno, ProfessorController professor, TurmaController turma) {
        this.aluno = aluno;
        this.professor = professor;
        this.turma = turma;
        initComponents();
    }
    
    public void setPosicao() {
        Dimension d = this.getDesktopPane().getSize();
        this.setLocation((d.width - this.getSize().width) / 2, (d.height - this.getSize().height) / 2);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        MI_AreaDeTrabalho = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        jbProfessor = new javax.swing.JPanel();
        Icone1 = new javax.swing.JLabel();
        Titulo1 = new javax.swing.JLabel();
        Titulo2 = new javax.swing.JLabel();
        jbAlunos = new javax.swing.JPanel();
        Icone2 = new javax.swing.JLabel();
        Titulo4 = new javax.swing.JLabel();
        Titulo5 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Lucida Fax", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Projeto/Public/images/books-stack-of-three.png"))); // NOI18N
        jLabel1.setText("  Disciplinas");

        jPanel3.setBackground(new java.awt.Color(102, 153, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 323, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );

        setClosable(true);
        setTitle("Membros da Instituição");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbProfessor.setBackground(new java.awt.Color(114, 120, 155));
        jbProfessor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbProfessor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbProfessorMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbProfessorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbProfessorMouseExited(evt);
            }
        });

        Icone1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Projeto/Public/images/professor.png"))); // NOI18N

        Titulo1.setFont(new java.awt.Font("Trebuchet MS", 0, 20)); // NOI18N
        Titulo1.setForeground(new java.awt.Color(255, 255, 255));
        Titulo1.setText("Professores");

        Titulo2.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        Titulo2.setForeground(new java.awt.Color(255, 255, 255));
        Titulo2.setText("Número de Professores");

        javax.swing.GroupLayout jbProfessorLayout = new javax.swing.GroupLayout(jbProfessor);
        jbProfessor.setLayout(jbProfessorLayout);
        jbProfessorLayout.setHorizontalGroup(
            jbProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jbProfessorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jbProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jbProfessorLayout.createSequentialGroup()
                        .addComponent(Icone1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 126, Short.MAX_VALUE)
                        .addComponent(Titulo2))
                    .addGroup(jbProfessorLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Titulo1)))
                .addContainerGap())
        );
        jbProfessorLayout.setVerticalGroup(
            jbProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jbProfessorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jbProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Icone1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Titulo2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Titulo1, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(jbProfessor, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, -1, -1));

        jbAlunos.setBackground(new java.awt.Color(55, 91, 163));
        jbAlunos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbAlunos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbAlunosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbAlunosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbAlunosMouseExited(evt);
            }
        });

        Icone2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Projeto/Public/images/student.png"))); // NOI18N

        Titulo4.setFont(new java.awt.Font("Trebuchet MS", 0, 20)); // NOI18N
        Titulo4.setForeground(new java.awt.Color(255, 255, 255));
        Titulo4.setText("Alunos");

        Titulo5.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        Titulo5.setForeground(new java.awt.Color(255, 255, 255));
        Titulo5.setText("Número de Alunos");

        javax.swing.GroupLayout jbAlunosLayout = new javax.swing.GroupLayout(jbAlunos);
        jbAlunos.setLayout(jbAlunosLayout);
        jbAlunosLayout.setHorizontalGroup(
            jbAlunosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jbAlunosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jbAlunosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jbAlunosLayout.createSequentialGroup()
                        .addComponent(Icone2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 154, Short.MAX_VALUE)
                        .addComponent(Titulo5))
                    .addGroup(jbAlunosLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Titulo4)))
                .addContainerGap())
        );
        jbAlunosLayout.setVerticalGroup(
            jbAlunosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jbAlunosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jbAlunosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Icone2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Titulo5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Titulo4, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(jbAlunos, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 210, -1, -1));

        jPanel4.setBackground(new java.awt.Color(31, 65, 132));

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Projeto/Public/images/team.png"))); // NOI18N
        jLabel2.setText("  MEMBROS DA INSTITUIÇÃO");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 980, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, 0, 1000, -1));

        MI_AreaDeTrabalho.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout MI_AreaDeTrabalhoLayout = new javax.swing.GroupLayout(MI_AreaDeTrabalho);
        MI_AreaDeTrabalho.setLayout(MI_AreaDeTrabalhoLayout);
        MI_AreaDeTrabalhoLayout.setHorizontalGroup(
            MI_AreaDeTrabalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 999, Short.MAX_VALUE)
        );
        MI_AreaDeTrabalhoLayout.setVerticalGroup(
            MI_AreaDeTrabalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MI_AreaDeTrabalhoLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 503, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MI_AreaDeTrabalho)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(MI_AreaDeTrabalho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void jbProfessorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbProfessorMouseClicked
        Professores frame = new Professores(professor, turma);
        MI_AreaDeTrabalho.add(frame);
        frame.setVisible(true);
        frame.setFrameIcon(new ImageIcon(RequisitosFuncionais.iconFrame));
        frame.setPosicao();
    }//GEN-LAST:event_jbProfessorMouseClicked

    private void jbAlunosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbAlunosMouseClicked
        Alunos frame = new Alunos(aluno);
        MI_AreaDeTrabalho.add(frame);
        frame.setVisible(true);
        frame.setFrameIcon(new ImageIcon(RequisitosFuncionais.iconFrame));
        frame.setPosicao();
    }//GEN-LAST:event_jbAlunosMouseClicked

    private void jbAlunosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbAlunosMouseEntered
        jbAlunos.setBackground(new java.awt.Color(25,52,105));
    }//GEN-LAST:event_jbAlunosMouseEntered

    private void jbAlunosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbAlunosMouseExited
        jbAlunos.setBackground(new java.awt.Color(55,91,163)); //COR ATUAL
    }//GEN-LAST:event_jbAlunosMouseExited

    private void jbProfessorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbProfessorMouseExited
        jbProfessor.setBackground(new java.awt.Color(114,120,155)); //COR ATUAL
    }//GEN-LAST:event_jbProfessorMouseExited

    private void jbProfessorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbProfessorMouseEntered
        jbProfessor.setBackground(new java.awt.Color(12,25,99));
    }//GEN-LAST:event_jbProfessorMouseEntered


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Icone1;
    private javax.swing.JLabel Icone2;
    private javax.swing.JDesktopPane MI_AreaDeTrabalho;
    private javax.swing.JLabel Titulo1;
    private javax.swing.JLabel Titulo2;
    private javax.swing.JLabel Titulo4;
    private javax.swing.JLabel Titulo5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jbAlunos;
    private javax.swing.JPanel jbProfessor;
    // End of variables declaration//GEN-END:variables
}
