/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Projeto.Views;

import Projeto.Classes.Flash;
import Projeto.Classes.Generator;
import Projeto.Classes.RequisitosFuncionais;
import Projeto.Controllers.*;
import java.awt.event.KeyEvent;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;

/**
 *
 * @author Leonardo
 */

public class Principal extends javax.swing.JFrame {

    AlunoController aluno = new AlunoController();
    ProfessorController professor = new ProfessorController();
    DisciplinaController disciplina = new DisciplinaController();
    TurmaController turma = new TurmaController();
    AlunoTurmaController aluno_turma = new AlunoTurmaController();
    HistoricoAlunoController historico_aluno = new HistoricoAlunoController();
    String buscarMatriculaAluno = null;
            
    public Principal() throws IOException {
        //this.setUndecorated(true);
        initComponents();
        this.setLocationRelativeTo(null);
        setIcon();
        
        //fakeGenerator();
             
    }
    
    private void setIcon() throws IOException {
        setIconImage(ImageIO.read(getClass().getResourceAsStream(RequisitosFuncionais.iconFrame)));
    }
    
    private void fakeGenerator(){
        for(int i=0; i<70; i++){
            String[] dados = {String.valueOf(Generator.getProximaMatricula()), "Aluno"+i};
            aluno.store(dados);
        }

        for(int i=0; i<40; i++){
            String[] dados = {String.valueOf(Generator.getProximaMatricula()), "Professor"+i};
            professor.store(dados);
        }

        for(int i=0; i<40; i++){
            String[] dados = {String.valueOf(Generator.getProximoId()), "Disciplina"+i};
            disciplina.store(dados);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AreaDeTrabalho = new javax.swing.JDesktopPane();
        jpBody = new javax.swing.JPanel();
        jbMembrosInstituicao = new javax.swing.JPanel();
        Icone1 = new javax.swing.JLabel();
        Titulo1 = new javax.swing.JLabel();
        Titulo2 = new javax.swing.JLabel();
        Titulo3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        tfBuscaAluno = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jbTurmas = new javax.swing.JPanel();
        Titulo4 = new javax.swing.JLabel();
        Icone2 = new javax.swing.JLabel();
        Titulo10 = new javax.swing.JLabel();
        jbCreditos = new javax.swing.JPanel();
        Icone3 = new javax.swing.JLabel();
        Titulo5 = new javax.swing.JLabel();
        Titulo9 = new javax.swing.JLabel();
        Titulo12 = new javax.swing.JLabel();
        jbDisciplinas = new javax.swing.JPanel();
        Icone4 = new javax.swing.JLabel();
        Titulo6 = new javax.swing.JLabel();
        Titulo11 = new javax.swing.JLabel();
        jbHistoricoDoAluno = new javax.swing.JPanel();
        Titulo7 = new javax.swing.JLabel();
        Icone5 = new javax.swing.JLabel();
        Titulo15 = new javax.swing.JLabel();
        jbNotas = new javax.swing.JPanel();
        Titulo8 = new javax.swing.JLabel();
        Icone6 = new javax.swing.JLabel();
        Titulo13 = new javax.swing.JLabel();
        Titulo14 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Projeto Minha Instituição");
        setResizable(false);

        jpBody.setBackground(new java.awt.Color(255, 255, 255));

        jbMembrosInstituicao.setBackground(new java.awt.Color(31, 37, 72));
        jbMembrosInstituicao.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbMembrosInstituicao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbMembrosInstituicaoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbMembrosInstituicaoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbMembrosInstituicaoMouseExited(evt);
            }
        });

        Icone1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Projeto/Public/images/team_white.png"))); // NOI18N

        Titulo1.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        Titulo1.setForeground(new java.awt.Color(255, 255, 255));
        Titulo1.setText("Membros da Instituição");

        Titulo2.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        Titulo2.setForeground(new java.awt.Color(255, 255, 255));
        Titulo2.setText("Alunos");

        Titulo3.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        Titulo3.setForeground(new java.awt.Color(255, 255, 255));
        Titulo3.setText("Professores");

        javax.swing.GroupLayout jbMembrosInstituicaoLayout = new javax.swing.GroupLayout(jbMembrosInstituicao);
        jbMembrosInstituicao.setLayout(jbMembrosInstituicaoLayout);
        jbMembrosInstituicaoLayout.setHorizontalGroup(
            jbMembrosInstituicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jbMembrosInstituicaoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jbMembrosInstituicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jbMembrosInstituicaoLayout.createSequentialGroup()
                        .addComponent(Icone1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jbMembrosInstituicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Titulo3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Titulo2, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jbMembrosInstituicaoLayout.createSequentialGroup()
                        .addGap(0, 159, Short.MAX_VALUE)
                        .addComponent(Titulo1)))
                .addContainerGap())
        );
        jbMembrosInstituicaoLayout.setVerticalGroup(
            jbMembrosInstituicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jbMembrosInstituicaoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jbMembrosInstituicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Icone1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jbMembrosInstituicaoLayout.createSequentialGroup()
                        .addComponent(Titulo2)
                        .addGap(2, 2, 2)
                        .addComponent(Titulo3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Titulo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 58, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        tfBuscaAluno.setFont(new java.awt.Font("Nirmala UI Semilight", 2, 12)); // NOI18N
        tfBuscaAluno.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfBuscaAluno.setText("Buscar Aluno...");
        tfBuscaAluno.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfBuscaAlunoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfBuscaAlunoFocusLost(evt);
            }
        });
        tfBuscaAluno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfBuscaAlunoKeyPressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 12)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Projeto/Public/images/exit.png"))); // NOI18N
        jLabel1.setText("Sair");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(tfBuscaAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfBuscaAluno)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jbTurmas.setBackground(new java.awt.Color(62, 64, 147));
        jbTurmas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbTurmas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbTurmasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbTurmasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbTurmasMouseExited(evt);
            }
        });

        Titulo4.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        Titulo4.setForeground(new java.awt.Color(255, 255, 255));
        Titulo4.setText("Turmas");

        Icone2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Projeto/Public/images/turmas.png"))); // NOI18N

        Titulo10.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        Titulo10.setForeground(new java.awt.Color(255, 255, 255));
        Titulo10.setText("Numero de Turmas");

        javax.swing.GroupLayout jbTurmasLayout = new javax.swing.GroupLayout(jbTurmas);
        jbTurmas.setLayout(jbTurmasLayout);
        jbTurmasLayout.setHorizontalGroup(
            jbTurmasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jbTurmasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jbTurmasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jbTurmasLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Titulo4))
                    .addGroup(jbTurmasLayout.createSequentialGroup()
                        .addComponent(Icone2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 164, Short.MAX_VALUE)
                        .addComponent(Titulo10)))
                .addContainerGap())
        );
        jbTurmasLayout.setVerticalGroup(
            jbTurmasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jbTurmasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jbTurmasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Icone2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Titulo10))
                .addGap(11, 11, 11)
                .addComponent(Titulo4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jbCreditos.setBackground(new java.awt.Color(88, 155, 210));
        jbCreditos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbCreditos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbCreditosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbCreditosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbCreditosMouseExited(evt);
            }
        });

        Icone3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Projeto/Public/images/customer.png"))); // NOI18N

        Titulo5.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        Titulo5.setForeground(new java.awt.Color(255, 255, 255));
        Titulo5.setText("Créditos");

        Titulo9.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        Titulo9.setForeground(new java.awt.Color(255, 255, 255));
        Titulo9.setText("Sobre o Projeto");

        Titulo12.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        Titulo12.setForeground(new java.awt.Color(255, 255, 255));
        Titulo12.setText("Quem sou eu?");

        javax.swing.GroupLayout jbCreditosLayout = new javax.swing.GroupLayout(jbCreditos);
        jbCreditos.setLayout(jbCreditosLayout);
        jbCreditosLayout.setHorizontalGroup(
            jbCreditosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jbCreditosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jbCreditosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jbCreditosLayout.createSequentialGroup()
                        .addComponent(Icone3, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 184, Short.MAX_VALUE)
                        .addGroup(jbCreditosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Titulo9, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Titulo12, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jbCreditosLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Titulo5)))
                .addContainerGap())
        );
        jbCreditosLayout.setVerticalGroup(
            jbCreditosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jbCreditosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jbCreditosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Icone3, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jbCreditosLayout.createSequentialGroup()
                        .addComponent(Titulo9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Titulo12)))
                .addGap(10, 10, 10)
                .addComponent(Titulo5, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                .addContainerGap())
        );

        jbDisciplinas.setBackground(new java.awt.Color(19, 118, 162));
        jbDisciplinas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbDisciplinas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbDisciplinasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbDisciplinasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbDisciplinasMouseExited(evt);
            }
        });

        Icone4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Projeto/Public/images/book.png"))); // NOI18N

        Titulo6.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        Titulo6.setForeground(new java.awt.Color(255, 255, 255));
        Titulo6.setText("Disciplinas");

        Titulo11.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        Titulo11.setForeground(new java.awt.Color(255, 255, 255));
        Titulo11.setText("Numero de Disciplinas");

        javax.swing.GroupLayout jbDisciplinasLayout = new javax.swing.GroupLayout(jbDisciplinas);
        jbDisciplinas.setLayout(jbDisciplinasLayout);
        jbDisciplinasLayout.setHorizontalGroup(
            jbDisciplinasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jbDisciplinasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jbDisciplinasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jbDisciplinasLayout.createSequentialGroup()
                        .addComponent(Icone4, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 146, Short.MAX_VALUE)
                        .addComponent(Titulo11))
                    .addGroup(jbDisciplinasLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Titulo6)))
                .addContainerGap())
        );
        jbDisciplinasLayout.setVerticalGroup(
            jbDisciplinasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jbDisciplinasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jbDisciplinasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Icone4, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Titulo11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(Titulo6, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                .addContainerGap())
        );

        jbHistoricoDoAluno.setBackground(new java.awt.Color(0, 166, 229));
        jbHistoricoDoAluno.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbHistoricoDoAluno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbHistoricoDoAlunoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbHistoricoDoAlunoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbHistoricoDoAlunoMouseExited(evt);
            }
        });

        Titulo7.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        Titulo7.setForeground(new java.awt.Color(255, 255, 255));
        Titulo7.setText("Histórico do Aluno");

        Icone5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Projeto/Public/images/tasks.png"))); // NOI18N

        Titulo15.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        Titulo15.setForeground(new java.awt.Color(255, 255, 255));
        Titulo15.setText("Detalhes sobre o aluno");

        javax.swing.GroupLayout jbHistoricoDoAlunoLayout = new javax.swing.GroupLayout(jbHistoricoDoAluno);
        jbHistoricoDoAluno.setLayout(jbHistoricoDoAlunoLayout);
        jbHistoricoDoAlunoLayout.setHorizontalGroup(
            jbHistoricoDoAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jbHistoricoDoAlunoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jbHistoricoDoAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jbHistoricoDoAlunoLayout.createSequentialGroup()
                        .addComponent(Icone5, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Titulo15))
                    .addGroup(jbHistoricoDoAlunoLayout.createSequentialGroup()
                        .addGap(0, 195, Short.MAX_VALUE)
                        .addComponent(Titulo7)))
                .addContainerGap())
        );
        jbHistoricoDoAlunoLayout.setVerticalGroup(
            jbHistoricoDoAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jbHistoricoDoAlunoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jbHistoricoDoAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Icone5, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Titulo15))
                .addGap(10, 10, 10)
                .addComponent(Titulo7, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                .addContainerGap())
        );

        jbNotas.setBackground(new java.awt.Color(114, 120, 155));
        jbNotas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbNotas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbNotasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbNotasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbNotasMouseExited(evt);
            }
        });

        Titulo8.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        Titulo8.setForeground(new java.awt.Color(255, 255, 255));
        Titulo8.setText("Matriculas e Notas");

        Icone6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Projeto/Public/images/notas.png"))); // NOI18N

        Titulo13.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        Titulo13.setForeground(new java.awt.Color(255, 255, 255));
        Titulo13.setText("Matricular alunos");

        Titulo14.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        Titulo14.setForeground(new java.awt.Color(255, 255, 255));
        Titulo14.setText("Atribuir notas");

        javax.swing.GroupLayout jbNotasLayout = new javax.swing.GroupLayout(jbNotas);
        jbNotas.setLayout(jbNotasLayout);
        jbNotasLayout.setHorizontalGroup(
            jbNotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jbNotasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Icone6, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 175, Short.MAX_VALUE)
                .addGroup(jbNotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Titulo13, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Titulo14, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jbNotasLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Titulo8, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jbNotasLayout.setVerticalGroup(
            jbNotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jbNotasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jbNotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Icone6, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jbNotasLayout.createSequentialGroup()
                        .addComponent(Titulo13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Titulo14)))
                .addGap(11, 11, 11)
                .addComponent(Titulo8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel2.setFont(new java.awt.Font("Meiryo", 0, 12)); // NOI18N
        jLabel2.setText("© 2017  Todos os direitos reservados, Leonardo Araujo");

        javax.swing.GroupLayout jpBodyLayout = new javax.swing.GroupLayout(jpBody);
        jpBody.setLayout(jpBodyLayout);
        jpBodyLayout.setHorizontalGroup(
            jpBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpBodyLayout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jpBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpBodyLayout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(jpBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpBodyLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 447, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(435, 435, 435))
                    .addGroup(jpBodyLayout.createSequentialGroup()
                        .addGroup(jpBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpBodyLayout.createSequentialGroup()
                                .addGap(378, 378, 378)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jpBodyLayout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addGroup(jpBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jbMembrosInstituicao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jbNotas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(jpBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jbTurmas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jbHistoricoDoAluno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(jpBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jbCreditos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jbDisciplinas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jpBodyLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jbCreditos, jbDisciplinas, jbHistoricoDoAluno, jbMembrosInstituicao, jbNotas, jbTurmas});

        jpBodyLayout.setVerticalGroup(
            jpBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpBodyLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addGroup(jpBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbMembrosInstituicao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbTurmas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbDisciplinas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbCreditos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbNotas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbHistoricoDoAluno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 119, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(16, 16, 16))
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jpBodyLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jbDisciplinas, jbTurmas});

        jpBodyLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jbCreditos, jbHistoricoDoAluno, jbMembrosInstituicao});

        AreaDeTrabalho.setLayer(jpBody, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout AreaDeTrabalhoLayout = new javax.swing.GroupLayout(AreaDeTrabalho);
        AreaDeTrabalho.setLayout(AreaDeTrabalhoLayout);
        AreaDeTrabalhoLayout.setHorizontalGroup(
            AreaDeTrabalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpBody, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        AreaDeTrabalhoLayout.setVerticalGroup(
            AreaDeTrabalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpBody, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AreaDeTrabalho)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AreaDeTrabalho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbMembrosInstituicaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbMembrosInstituicaoMouseClicked
        MembrosInstituicao frame = new MembrosInstituicao(aluno, professor, turma);
        AreaDeTrabalho.add(frame);
        frame.setVisible(true);
        frame.setFrameIcon(new ImageIcon(this.getIconImage()));
        frame.setPosicao();
    }//GEN-LAST:event_jbMembrosInstituicaoMouseClicked

    private void jbTurmasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbTurmasMouseClicked
        Turmas frame = new Turmas(disciplina, turma, professor, aluno_turma);
        AreaDeTrabalho.add(frame);
        frame.setVisible(true);
        frame.setFrameIcon(new ImageIcon(this.getIconImage()));
        frame.setPosicao();
    }//GEN-LAST:event_jbTurmasMouseClicked

    private void jbCreditosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbCreditosMouseClicked
        Creditos frame = new Creditos();
        AreaDeTrabalho.add(frame);
        frame.setVisible(true);
        frame.setFrameIcon(new ImageIcon(this.getIconImage()));
        frame.setPosicao();
    }//GEN-LAST:event_jbCreditosMouseClicked

    private void jbDisciplinasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbDisciplinasMouseClicked
        Disciplinas frame = new Disciplinas(disciplina, turma);
        AreaDeTrabalho.add(frame);
        frame.setVisible(true);
        frame.setFrameIcon(new ImageIcon(this.getIconImage()));
        frame.setPosicao();
    }//GEN-LAST:event_jbDisciplinasMouseClicked

    private void jbHistoricoDoAlunoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbHistoricoDoAlunoMouseClicked
        buscarMatriculaAluno = String.valueOf(Flash.input("Informe a matricula do aluno?", "loupe")); 
        
        if(!buscarMatriculaAluno.equals("null") && !buscarMatriculaAluno.isEmpty()){            
            Object[] controllers = { aluno, professor, disciplina, turma, aluno_turma, historico_aluno };
            HistoricoAluno frame = new HistoricoAluno(buscarMatriculaAluno, controllers);
            AreaDeTrabalho.add(frame);
            frame.setVisible(true);
            frame.setFrameIcon(new ImageIcon(this.getIconImage()));
            frame.setPosicao();
        }
    }//GEN-LAST:event_jbHistoricoDoAlunoMouseClicked

    private void tfBuscaAlunoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfBuscaAlunoKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            buscarMatriculaAluno = tfBuscaAluno.getText(); 
            if( !buscarMatriculaAluno.isEmpty() ){
                Object[] controllers = { aluno, professor, disciplina, turma, aluno_turma, historico_aluno };
                HistoricoAluno frame = new HistoricoAluno(buscarMatriculaAluno, controllers);
                AreaDeTrabalho.add(frame);
                frame.setVisible(true);
                frame.setFrameIcon(new ImageIcon(this.getIconImage()));
                frame.setPosicao();
            }else{
                Flash.error("Erro na pesquisa pelo aluno.");
            }
        }
    }//GEN-LAST:event_tfBuscaAlunoKeyPressed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        if (Flash.confirm("Deseja encerrar o aplicativo?", "remove") == 0) 
            System.exit(0);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jbNotasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbNotasMouseClicked
        Object[] controllers = { disciplina, turma, aluno_turma, professor, aluno, historico_aluno };
        MatriculaNotasAlunos frame = new MatriculaNotasAlunos(controllers);
        AreaDeTrabalho.add(frame);
        frame.setVisible(true);
        frame.setFrameIcon(new ImageIcon(this.getIconImage()));
        frame.setPosicao();
    }//GEN-LAST:event_jbNotasMouseClicked

    private void tfBuscaAlunoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfBuscaAlunoFocusGained
        tfBuscaAluno.setText("");
    }//GEN-LAST:event_tfBuscaAlunoFocusGained

    private void tfBuscaAlunoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfBuscaAlunoFocusLost
        tfBuscaAluno.setText("Buscar Aluno...");
    }//GEN-LAST:event_tfBuscaAlunoFocusLost

    private void jbMembrosInstituicaoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbMembrosInstituicaoMouseEntered
        jbMembrosInstituicao.setBackground(new java.awt.Color(59,67,112));
    }//GEN-LAST:event_jbMembrosInstituicaoMouseEntered

    private void jbMembrosInstituicaoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbMembrosInstituicaoMouseExited
        jbMembrosInstituicao.setBackground(new java.awt.Color(31, 37, 72)); //COR ATUAL
    }//GEN-LAST:event_jbMembrosInstituicaoMouseExited

    private void jbTurmasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbTurmasMouseEntered
        jbTurmas.setBackground(new java.awt.Color(40,42,106));
    }//GEN-LAST:event_jbTurmasMouseEntered

    private void jbTurmasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbTurmasMouseExited
        jbTurmas.setBackground(new java.awt.Color(62,64,147)); //COR ATUAL
    }//GEN-LAST:event_jbTurmasMouseExited

    private void jbDisciplinasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbDisciplinasMouseExited
        jbDisciplinas.setBackground(new java.awt.Color(19,118,162)); //COR ATUAL
    }//GEN-LAST:event_jbDisciplinasMouseExited

    private void jbDisciplinasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbDisciplinasMouseEntered
        jbDisciplinas.setBackground(new java.awt.Color(15,85,117));
    }//GEN-LAST:event_jbDisciplinasMouseEntered

    private void jbNotasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbNotasMouseEntered
        jbNotas.setBackground(new java.awt.Color(75,82,123));
    }//GEN-LAST:event_jbNotasMouseEntered

    private void jbNotasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbNotasMouseExited
        jbNotas.setBackground(new java.awt.Color(114,120,155)); //COR ATUAL
    }//GEN-LAST:event_jbNotasMouseExited

    private void jbHistoricoDoAlunoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbHistoricoDoAlunoMouseExited
        jbHistoricoDoAluno.setBackground(new java.awt.Color(0,166,229)); //COR ATUAL
    }//GEN-LAST:event_jbHistoricoDoAlunoMouseExited

    private void jbHistoricoDoAlunoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbHistoricoDoAlunoMouseEntered
        jbHistoricoDoAluno.setBackground(new java.awt.Color(11,122,164));
    }//GEN-LAST:event_jbHistoricoDoAlunoMouseEntered

    private void jbCreditosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbCreditosMouseExited
        jbCreditos.setBackground(new java.awt.Color(88,155,210)); //COR ATUAL
    }//GEN-LAST:event_jbCreditosMouseExited

    private void jbCreditosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbCreditosMouseEntered
        jbCreditos.setBackground(new java.awt.Color(62,114,157));
    }//GEN-LAST:event_jbCreditosMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new Principal().setVisible(true);
            } catch (IOException ex) {
                Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane AreaDeTrabalho;
    private javax.swing.JLabel Icone1;
    private javax.swing.JLabel Icone2;
    private javax.swing.JLabel Icone3;
    private javax.swing.JLabel Icone4;
    private javax.swing.JLabel Icone5;
    private javax.swing.JLabel Icone6;
    private javax.swing.JLabel Titulo1;
    private javax.swing.JLabel Titulo10;
    private javax.swing.JLabel Titulo11;
    private javax.swing.JLabel Titulo12;
    private javax.swing.JLabel Titulo13;
    private javax.swing.JLabel Titulo14;
    private javax.swing.JLabel Titulo15;
    private javax.swing.JLabel Titulo2;
    private javax.swing.JLabel Titulo3;
    private javax.swing.JLabel Titulo4;
    private javax.swing.JLabel Titulo5;
    private javax.swing.JLabel Titulo6;
    private javax.swing.JLabel Titulo7;
    private javax.swing.JLabel Titulo8;
    private javax.swing.JLabel Titulo9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel jbCreditos;
    private javax.swing.JPanel jbDisciplinas;
    private javax.swing.JPanel jbHistoricoDoAluno;
    private javax.swing.JPanel jbMembrosInstituicao;
    private javax.swing.JPanel jbNotas;
    private javax.swing.JPanel jbTurmas;
    private javax.swing.JPanel jpBody;
    private javax.swing.JTextField tfBuscaAluno;
    // End of variables declaration//GEN-END:variables
}
