/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Projeto.Views.membros;

import Projeto.Classes.*;
import Projeto.Controllers.ProfessorController;
import Projeto.Controllers.TurmaController;
import Projeto.Models.Professor;
import java.awt.Dimension;
import java.awt.event.KeyEvent;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Leonardo
 */
public final class Professores extends javax.swing.JInternalFrame {
    
    ProfessorController professor;
    TurmaController turma;
    String modo = "Criar";
     
    /** Creates new form jProfessores
     * @param professor
     * @param turma */
    public Professores(ProfessorController professor, TurmaController turma) {
        // variaveis da classe recebe dados do controller inicializado no main
        this.professor = professor;
        this.turma = turma;
        initComponents();
        carregaTabela();
        controleCampos(false);
        jbEditar.setEnabled(false);
        jbRemover.setEnabled(false);
        jbSalvar.setEnabled(false);
    }
    
    public void carregaTabela(){
        DefaultTableModel modelo = new DefaultTableModel(new Object[]{ "Matricula", "Nome" }, 0 ){
            @Override
            public boolean isCellEditable(int row, int column) { 
                return false;
            }
        };
        
        for( int i=0; i < professor.index().size(); i++){
            modelo.addRow(new Object[]{ 
                professor.index().get(i).getMatricula(), 
                professor.index().get(i).getNome()
            });
        }
        modelo.isCellEditable(0, 0);
        TableProfessor.setModel(modelo);
    }
    
    public void setPosicao() {
        Dimension d = this.getDesktopPane().getSize();
        this.setLocation((d.width - this.getSize().width) / 2, (d.height - this.getSize().height) / 2);
    }
  
    private void limpaCampos(){
        tfMatricula.setText("");
        tfNome.setText("");
    }
     
    private void controleCampos(boolean status){
        tfMatricula.setEnabled(false);
        tfNome.setEnabled(status);
    }
     
    private void cadastrarEditar(){
        String[] dados = { tfMatricula.getText(), tfNome.getText() };
        
        if( !tfNome.getText().equals("") ){
            if(modo.equals("Criar")){
                professor.store(dados);
                Flash.success("Professor matriculado.");
                
                jbSalvar.setEnabled(false);
                jbNovo.setEnabled(true);
                jbEditar.setEnabled(false);
                jbRemover.setEnabled(false);
        
            }else if(modo.equals("Editar")){
                professor.update(dados, Integer.valueOf(TableProfessor.getValueAt(TableProfessor.getSelectedRow(), 0).toString()));    
                Flash.success("Informações salvas.");
                
                jbSalvar.setText("Matricular");
                
                jbSalvar.setEnabled(false);
                jbNovo.setEnabled(true);
                jbEditar.setEnabled(false);
                jbRemover.setEnabled(false);
            }
            
            carregaTabela();  
            limpaCampos();
            controleCampos(false);
            
        }else{
            Flash.error("Alguns campos não devem ficar vazios.");
        }
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jbEditar = new javax.swing.JButton();
        jbRemover = new javax.swing.JButton();
        jbNovo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableProfessor = new javax.swing.JTable();
        jbSalvar = new javax.swing.JButton();
        tfMatricula = new javax.swing.JTextField();
        tfNome = new javax.swing.JTextField();
        jlMatricula = new javax.swing.JLabel();
        jlNome = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Professores");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jbEditar.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jbEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Projeto/Public/icons/edit.png"))); // NOI18N
        jbEditar.setText("Editar");
        jbEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEditarActionPerformed(evt);
            }
        });

        jbRemover.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jbRemover.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Projeto/Public/icons/substract.png"))); // NOI18N
        jbRemover.setText("Desmatricular");
        jbRemover.setPreferredSize(new java.awt.Dimension(89, 25));
        jbRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbRemoverActionPerformed(evt);
            }
        });

        jbNovo.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jbNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Projeto/Public/icons/add.png"))); // NOI18N
        jbNovo.setText("Novo");
        jbNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNovoActionPerformed(evt);
            }
        });

        TableProfessor.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        TableProfessor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TableProfessor.setSelectionBackground(new java.awt.Color(26, 79, 121));
        TableProfessor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableProfessorMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TableProfessor);

        jbSalvar.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jbSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Projeto/Public/icons/checked.png"))); // NOI18N
        jbSalvar.setText("Salvar");
        jbSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalvarActionPerformed(evt);
            }
        });

        tfMatricula.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N

        tfNome.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        tfNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfNomeKeyPressed(evt);
            }
        });

        jlMatricula.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jlMatricula.setText("Matricula:");

        jlNome.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jlNome.setText("Nome:");

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jPanel3.setBackground(new java.awt.Color(82, 77, 159));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Projeto/Public/images/teacher.png"))); // NOI18N
        jLabel1.setText("  PROFESSORES");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlNome, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jlMatricula, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfNome)
                            .addComponent(tfMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jbNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbSalvar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jbRemover, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbEditar, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE))))
                .addGap(32, 32, 32)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jbEditar, jbNovo, jbRemover, jbSalvar});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tfMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jlMatricula))
                                .addGap(19, 19, 19)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jlNome))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jbEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jbRemover, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbSalvar))
                                .addGap(37, 37, 37))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {tfMatricula, tfNome});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jbEditar, jbNovo, jbRemover, jbSalvar});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalvarActionPerformed
        cadastrarEditar();
    }//GEN-LAST:event_jbSalvarActionPerformed

    private void jbEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEditarActionPerformed
        int linha = TableProfessor.getSelectedRow();
        
        if( linha>=0 && linha < professor.index().size() ){
            Professor p = professor.search(Integer.valueOf(TableProfessor.getValueAt(linha, 0).toString()));
            tfMatricula.setText( String.valueOf(p.getMatricula()) );
            tfNome.setText(p.getNome());
            modo = "Editar";
            
            jbSalvar.setText("Modificar");
            controleCampos(true);

            jbSalvar.setEnabled(true);
            jbNovo.setEnabled(false);
            jbEditar.setEnabled(true);
            jbRemover.setEnabled(true);
            
        }        
    }//GEN-LAST:event_jbEditarActionPerformed

    private void jbRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbRemoverActionPerformed
        int linha = TableProfessor.getSelectedRow();
        if( linha>=0 && linha < professor.index().size() ){
            if (Flash.confirm("Deseja desmatricular esse professor?", "warning") == 0) {
                if( turma.buscaProfessor(Integer.valueOf(TableProfessor.getValueAt(linha, 0).toString())) ){
                    professor.delete(Integer.valueOf(TableProfessor.getValueAt(linha, 0).toString()));
                    carregaTabela();
                    limpaCampos();
                    jbSalvar.setEnabled(false);
                    jbNovo.setEnabled(true);
                    jbEditar.setEnabled(false);
                    jbRemover.setEnabled(false);
                    controleCampos(false);
                }else{
                    Flash.warning("Professor vinculado a turma(s). Encerre-a primeiro, para remover.");                    
                }
            }
        }
    }//GEN-LAST:event_jbRemoverActionPerformed

    private void jbNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNovoActionPerformed
        if( professor.index().size() <= RequisitosFuncionais.quantidadeProfessores ){
            jbSalvar.setEnabled(true);
            jbNovo.setEnabled(false);
            jbEditar.setEnabled(false);
            jbRemover.setEnabled(false);

            controleCampos(true);
            jbSalvar.setText("Matricular");

            limpaCampos();
            modo = "Criar";
            tfMatricula.setText( String.valueOf(Generator.getProximaMatricula()) );
            tfNome.requestFocus();
        }else{
            Flash.warning("Número máximo de professores permitidos.");
        }
    }//GEN-LAST:event_jbNovoActionPerformed

    private void TableProfessorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableProfessorMouseClicked
        jbSalvar.setEnabled(false);
        jbNovo.setEnabled(true);
        jbEditar.setEnabled(true);
        jbRemover.setEnabled(true);
        limpaCampos();
        controleCampos(false);
    }//GEN-LAST:event_TableProfessorMouseClicked

    private void tfNomeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfNomeKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) 
            cadastrarEditar();
    }//GEN-LAST:event_tfNomeKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TableProfessor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton jbEditar;
    private javax.swing.JButton jbNovo;
    private javax.swing.JButton jbRemover;
    private javax.swing.JButton jbSalvar;
    private javax.swing.JLabel jlMatricula;
    private javax.swing.JLabel jlNome;
    private javax.swing.JTextField tfMatricula;
    private javax.swing.JTextField tfNome;
    // End of variables declaration//GEN-END:variables

}
